import assert from 'node:assert/strict'
import { test } from 'node:test'
import { isHotspotCandidate, rankHotspots, topHotspotCount } from '../src/hotspots.ts'

const file = (id: string, churn: number, loc: number) => ({ id, churn, loc })

test('ranks by commits × lines', () => {
  const ranked = rankHotspots([
    file('src/big-and-busy.ts', 50, 2000), // 100,000
    file('src/busy-but-tiny.ts', 200, 20), // 4,000
    file('src/big-but-quiet.ts', 1, 3000), // 3,000
  ])
  assert.deepEqual(
    [...ranked].map(([id, h]) => [id, h.rank]),
    [
      ['src/big-and-busy.ts', 1],
      ['src/busy-but-tiny.ts', 2],
      ['src/big-but-quiet.ts', 3],
    ],
  )
})

test('scores are log-scaled between 0 and 1, with the top file at 1', () => {
  const ranked = rankHotspots([file('a.ts', 100, 1000), file('b.ts', 10, 100), file('c.ts', 1, 10)])
  assert.equal(ranked.get('a.ts')!.score, 1)
  const b = ranked.get('b.ts')!.score
  const c = ranked.get('c.ts')!.score
  assert.ok(b > c && c > 0 && b < 1)
  // a linear scale would put b at 0.01; the log keeps the middle distinguishable
  assert.ok(b > 0.5)
})

test('files not changed in the last year are not hotspots', () => {
  const ranked = rankHotspots([file('src/stable.ts', 0, 5000), file('src/changed.ts', 3, 10)])
  assert.equal(ranked.has('src/stable.ts'), false)
  assert.equal(ranked.get('src/changed.ts')!.rank, 1)
})

test('ignores data, generated files and tests', () => {
  for (const id of [
    'src/lang/en-US.autogenerated.json',
    'src/api.generated.ts',
    'src/order/order.service.test.ts',
    'src/order/order.service.spec.tsx',
    'src/test/account.mock.ts',
    'src/__tests__/a.ts',
    'src/ui/button.stories.tsx',
  ]) {
    assert.equal(isHotspotCandidate(id), false, id)
  }
  for (const id of ['src/order/order.service.ts', 'src/testing-utils.ts', 'src/contest/contest.ts']) {
    assert.equal(isHotspotCandidate(id), true, id)
  }
})

test('handles no history at all', () => {
  assert.equal(rankHotspots([file('a.ts', 0, 10)]).size, 0)
  assert.equal(topHotspotCount(0), 0)
})

test('flags the top 2% as top hotspots, and at least one', () => {
  assert.equal(topHotspotCount(1300), 26)
  assert.equal(topHotspotCount(10), 1)
})
