/**
 * Hotspots: code that is both large and changed often, after Adam Tornhill's "Your Code as a Crime
 * Scene". Lines of code stand in for complexity, and commits in the last year for change frequency.
 * A file that is big but never touched, or touched constantly but tiny, isn't a hotspot; one that
 * is both is where bugs and slow changes concentrate, so it's usually the best place to refactor first.
 */

/** Files that aren't hand-written production code: data, generated output and tests */
const NOT_A_HOTSPOT =
  /\.json$|\.(generated|autogenerated)\.|(^|\/)(__tests__|__mocks__|__fixtures__|tests?|fixtures?|mocks?)\/|\.(test|spec|mock|stories)\.[cm]?[jt]sx?$/

/** Share of ranked files flagged as top hotspots */
export const TOP_HOTSPOT_SHARE = 0.02

export interface HotspotInput {
  id: string
  /** Commits touching the file in the last year */
  churn: number
  loc: number
}

export interface Hotspot {
  /** 0–1: log-scaled commits × lines, relative to the biggest hotspot */
  score: number
  /** 1 = biggest hotspot */
  rank: number
}

export const isHotspotCandidate = (id: string) => !NOT_A_HOTSPOT.test(id)

/**
 * Ranks files by commits × lines. Files that are excluded, or weren't changed in the last year,
 * aren't ranked. The score is log-scaled because the product is heavily skewed: without the log,
 * everything but the top few files would score close to 0.
 */
export function rankHotspots(files: HotspotInput[]): Map<string, Hotspot> {
  const ranked = files
    .filter(f => f.churn > 0 && f.loc > 0 && isHotspotCandidate(f.id))
    .map(f => ({ id: f.id, effort: f.churn * f.loc }))
    .toSorted((a, b) => b.effort - a.effort || (a.id < b.id ? -1 : 1))
  const max = Math.log1p(ranked[0]?.effort ?? 0) || 1
  return new Map(ranked.map((f, i) => [f.id, { score: Math.log1p(f.effort) / max, rank: i + 1 }]))
}

/** How many of the ranked files count as top hotspots */
export const topHotspotCount = (ranked: number) => (ranked ? Math.max(1, Math.round(ranked * TOP_HOTSPOT_SHARE)) : 0)
